# Commitlint configuration for Conventional Commits
# https://www.conventionalcommits.org/

extends:
  - '@commitlint/config-conventional'

rules:
  # Type must be one of the following
  type-enum:
    - 2  # Error level
    - always
    - - feat      # New feature
      - fix       # Bug fix
      - docs      # Documentation only
      - style     # Formatting, no code change
      - refactor  # Code change that neither fixes nor adds
      - perf      # Performance improvement
      - test      # Adding or updating tests
      - build     # Build system or dependencies
      - ci        # CI configuration
      - chore     # Maintenance tasks
      - revert    # Revert a commit

  # Scope is optional but recommended
  scope-enum:
    - 1  # Warning level
    - always
    - - core      # Core NoC components (router, ni, mesh)
      - flit      # Flit and packet handling
      - routing   # Routing selector and algorithms
      - testbench # Test bench components (memory, axi_master)
      - verify    # Verification and validation
      - config    # Configuration
      - docs      # Documentation
      - test      # Test infrastructure
      - ci        # CI/CD
      - deps      # Dependencies

  # Subject rules
  subject-case:
    - 2
    - always
    - - lower-case
      - sentence-case

  subject-empty:
    - 2
    - never

  subject-full-stop:
    - 2
    - never
    - '.'

  # Header max length
  header-max-length:
    - 2
    - always
    - 100

  # Body rules
  body-leading-blank:
    - 2
    - always

  body-max-line-length:
    - 1
    - always
    - 100

  # Footer rules
  footer-leading-blank:
    - 2
    - always
